### ISSUE TITLE
implement following-tracking

### ISSUE THREAD

**Issue by eljojo** [eljojo/pepe#1]
we should probably have a separate table/model where we keep track of who we follow.

- [x] seed with all the accounts returned by the ``:friends`` event when connecting to twitter
- [x] remove accounts that are in the database but not in the list
- [x] remove accounts on :unfollow event and add accounts on :follow event
- [x] don't show users in the list of users when they're unfollowed
